name: diagnostics
on:
  push:
    branches:
      - diag

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      baseline-sha-long: ${{steps.commit.outputs.baseline-long}}
      baseline-sha: ${{steps.commit.outputs.baseline}}
      topic-sha: ${{steps.commit.outputs.topic}}
      ra-baseline: ra-bb/rust-analyzer-baseline-${{steps.commit.outputs.baseline}}
      ra-topic: ra-bb/rust-analyzer-topic-${{steps.commit.outputs.topic}}
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rust-src

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Find commits
        id: commit
        run: |
          echo Excluding the last commit that adds this workflow file
          echo "::set-output name=baseline-long::$(git rev-list --author=bors -n1 HEAD)"
          echo "::set-output name=baseline::$(git rev-list --abbrev-commit --author=bors -n1 HEAD)"
          echo "::set-output name=topic::$(git rev-list --abbrev-commit -n1 HEAD^)"

      - run: mkdir -p ra-bb

      # - uses: actions/cache@v2
      #   id: bb-cache
      #   with:
      #     key: bb-cache_${{runner.os}}_${{steps.commit.outputs.baseline}}..${{steps.commit.outputs.topic}}
      #     path: ra-bb/

      - uses: Swatinem/rust-cache@ce325b60658c1b38465c06cc965b79baf32c1e72
        # if: steps.bb-cache.outputs.cache-hit != 'true'

      - name: Switch to topic
        # if: steps.bb-cache.outputs.cache-hit != 'true'
        run: |
          git checkout ${{steps.commit.outputs.topic}}
          git log -n1
          cargo fetch --locked --target x86_64-unknown-linux-gnu

      - name: Build topic
        # if: steps.bb-cache.outputs.cache-hit != 'true'
        run: |
          cargo xtask bb topic-${{steps.commit.outputs.topic}}
          mv target/rust-analyzer-topic-${{steps.commit.outputs.topic}} ra-bb/

      # - name: Switch to baseline
      #   # if: steps.bb-cache.outputs.cache-hit != 'true'
      #   run: |
      #     git checkout ${{steps.commit.outputs.baseline}}
      #     git log -n1
      #     cargo fetch --locked --target x86_64-unknown-linux-gnu

      # - name: Build baseline
      #   # if: steps.bb-cache.outputs.cache-hit != 'true'
      #   run: |
      #     cargo xtask bb baseline-${{steps.commit.outputs.baseline}}
      #     mv target/rust-analyzer-baseline-${{steps.commit.outputs.baseline}} ra-bb/

      - name: Compress artifacts
        run: tar -I 'zstd -T0 -12 --long' -vcf ra-bb-x86_64-unknown-linux-gnu.tar.zst ra-bb/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ra-bb-x86_64-unknown-linux-gnu
          path: ra-bb-x86_64-unknown-linux-gnu.tar.zst

  diagnostics:
    name: Diagnostics
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target-repo: [self, ripgrep, webrender, diesel, creusot]
        # ra: [baseline, topic]
        ra: [topic]
        include:
          - target-repo: self
            target-repo-path: ra-src-baseline
          - target-repo: ripgrep
            target-repo-path: rustc-perf/collector/benchmarks/ripgrep
          - target-repo: webrender
            target-repo-path: rustc-perf/collector/benchmarks/webrender
          - target-repo: diesel
            target-repo-path: rustc-perf/collector/benchmarks/diesel/diesel
          - target-repo: creusot
            target-repo-path: creusot
          # - ra: baseline
          #   ra-path: ${{needs.build.outputs.ra-baseline}}
          - ra: topic
            ra-path: ${{needs.build.outputs.ra-topic}}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ra-bb-x86_64-unknown-linux-gnu

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@ce325b60658c1b38465c06cc965b79baf32c1e72

      - name: Restore artifacts
        run: |
          tar -vxf ra-bb-x86_64-unknown-linux-gnu.tar.zst
          mkdir -p diagnostics

      - uses: actions/checkout@v2
        if: matrix.target-repo == 'self'
        with:
          ref: ${{needs.build.outputs.baseline-sha-long}}
          path: ${{matrix.target-repo-path}}

      - uses: actions/checkout@v2
        if: startsWith(matrix.target-repo-path, 'rustc-perf')
        with:
          repository: rust-lang/rustc-perf
          ref: c52ee623e231e7690a93be88d943016968c1036b
          path: rustc-perf

      - uses: actions/checkout@v2
        if: matrix.target-repo == 'creusot'
        with:
          repository: xldenis/creusot
          ref: d5ef5ddc51a8ef4ba736d4bab537800e1b0df2d5
          path: creusot

      - if: matrix.target-repo == 'creusot'
        run: rustup toolchain install nightly-2022-01-15 -c rustfmt -c rustc-dev -c llvm-tools-preview

      - name: Collect diagnostics
        run: ${{matrix.ra-path}} diagnostics --disable-build-scripts ${{matrix.target-repo-path}} # |& tee diagnostics/${{matrix.target-repo}}-${{matrix.ra}}

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: diag-${{matrix.target-repo}}-${{matrix.ra}}
      #     path: diagnostics/*

  # diff:
  #   name: Diff diagnostics
  #   needs: diagnostics
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       target-repo: [self, ripgrep, webrender, diesel]
  #     fail-fast: false
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: diag-${{matrix.target-repo}}-baseline
  #         path: diagnostics
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: diag-${{matrix.target-repo}}-topic
  #         path: diagnostics

  #     - name: Diff diagnostics
  #       continue-on-error: true
  #       run: |
  #         ls -l diagnostics/
  #         git diff --no-index diagnostics/* | tee diag-${{matrix.target-repo}}.diff

  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: diag-${{matrix.target-repo}}.diff
  #         path: diag-${{matrix.target-repo}}.diff

  #     - name: fail if diagnostics differ
  #       run: git diff --no-index --numstat diagnostics/*
