name: exhaustive_patterns.diagnostics
on:
  push:
    branches:
      - exhaustive_patterns.diagnostics

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      baseline-sha-long: ${{steps.commit.outputs.baseline-long}}
      baseline-sha: ${{steps.commit.outputs.baseline}}
      topic-sha: ${{steps.commit.outputs.topic}}
      ra-baseline: ra-bb/rust-analyzer-baseline-${{steps.commit.outputs.baseline}}
      ra-topic: ra-bb/rust-analyzer-topic-${{steps.commit.outputs.topic}}
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rust-src

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Find commits
        id: commit
        run: |
          echo Excluding the last commit that adds this workflow file
          echo "::set-output name=baseline-long::$(git rev-list --author=bors -n1 HEAD)"
          echo "::set-output name=baseline::$(git rev-list --abbrev-commit --author=bors -n1 HEAD)"
          echo "::set-output name=topic::$(git rev-list --abbrev-commit -n1 HEAD^)"

      - run: mkdir -p ra-bb

      - uses: actions/cache@v2
        id: bb-cache
        with:
          key: bb-cache_${{runner.os}}_${{steps.commit.outputs.baseline}}..${{steps.commit.outputs.topic}}
          path: ra-bb/

      - uses: Swatinem/rust-cache@ce325b60658c1b38465c06cc965b79baf32c1e72
        if: steps.bb-cache.outputs.cache-hit != 'true'

      - name: Switch to topic
        if: steps.bb-cache.outputs.cache-hit != 'true'
        run: |
          git checkout ${{steps.commit.outputs.topic}}
          git log -n1
          cargo fetch --locked --target x86_64-unknown-linux-gnu

      - name: Build topic
        if: steps.bb-cache.outputs.cache-hit != 'true'
        run: |
          cargo xtask bb topic-${{steps.commit.outputs.topic}}
          mv target/rust-analyzer-topic-${{steps.commit.outputs.topic}} ra-bb/

      - name: Switch to baseline
        if: steps.bb-cache.outputs.cache-hit != 'true'
        run: |
          git checkout ${{steps.commit.outputs.baseline}}
          git log -n1
          cargo fetch --locked --target x86_64-unknown-linux-gnu

      - name: Build baseline
        if: steps.bb-cache.outputs.cache-hit != 'true'
        run: |
          cargo xtask bb baseline-${{steps.commit.outputs.baseline}}
          mv target/rust-analyzer-baseline-${{steps.commit.outputs.baseline}} ra-bb/

      - name: Compress artifacts
        run: tar -I 'zstd -T0 -12 --long' -vcf ra-bb-x86_64-unknown-linux-gnu.tar.zst ra-bb/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ra-bb-x86_64-unknown-linux-gnu
          path: ra-bb-x86_64-unknown-linux-gnu.tar.zst

  diagnostics:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # target: [self, ripgrep, webrender, diesel, creusot]
        target: [self, ripgrep, webrender, creusot, rust]
        # ra: [baseline, topic]
        include:
          # Default repo to checkout
          - repository: rust-lang/rustc-perf
            ref: c52ee623e231e7690a93be88d943016968c1036b
            path: rustc-perf

          - target: self
            repository: ${{ github.repository }}
            ref: ${{needs.build.outputs.baseline-sha-long}}
            path: ra-src-baseline
            target-path: ra-src-baseline

          - target: ripgrep
            target-path: rustc-perf/collector/benchmarks/ripgrep

          - target: webrender
            target-path: rustc-perf/collector/benchmarks/webrender

          # - target: diesel
          #   target-path: rustc-perf/collector/benchmarks/diesel/diesel

          - target: creusot
            repository: xldenis/creusot
            ref: d5ef5ddc51a8ef4ba736d4bab537800e1b0df2d5
            path: creusot
            target-path: creusot

          - target: rust
            repository: rust-lang/rust
            ref: 8f68c43ca6a6381a4d73f887f112e9fb95769905
            path: rust
            target-path: rust

          # - ra: baseline
          #   ra-path: ${{needs.build.outputs.ra-baseline}}
          # - ra: topic
          #   ra-path: ${{needs.build.outputs.ra-topic}}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ra-bb-x86_64-unknown-linux-gnu

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@ce325b60658c1b38465c06cc965b79baf32c1e72

      - name: Restore artifacts
        run: |
          tar -vxf ra-bb-x86_64-unknown-linux-gnu.tar.zst
          mkdir -p stats

      - uses: actions/checkout@v2
        with:
          repository: ${{matrix.repository}}
          ref: ${{matrix.ref}}
          path: ${{matrix.path}}

      - if: matrix.target == 'creusot'
        run: rustup toolchain install nightly-2022-01-15 -c rustfmt -c rustc-dev -c llvm-tools-preview

      - name: Exclude rust tools
        if: matrix.target == 'rust'
        run: |
          cd rust
          ls -l
          git apply <(cat <<EOF
          diff --git a/Cargo.toml b/Cargo.toml
          index ffc886d47..edf2c45a1 100644
          --- a/Cargo.toml
          +++ b/Cargo.toml
          @@ -8,2 +8,2 @@ members = [
          -  "src/tools/clippy",
          -  "src/tools/clippy/clippy_dev",
          +  # "src/tools/clippy",
          +  # "src/tools/clippy/clippy_dev",
          @@ -14 +14 @@ members = [
          -  "src/tools/rustbook",
          +  # "src/tools/rustbook",
          @@ -19,3 +19,3 @@ members = [
          -  "src/tools/remote-test-client",
          -  "src/tools/remote-test-server",
          -  "src/tools/rust-installer",
          +  # "src/tools/remote-test-client",
          +  # "src/tools/remote-test-server",
          +  # "src/tools/rust-installer",
          @@ -23,6 +23,6 @@ members = [
          -  "src/tools/cargo",
          -  "src/tools/cargo/crates/credential/cargo-credential-1password",
          -  "src/tools/cargo/crates/credential/cargo-credential-macos-keychain",
          -  "src/tools/cargo/crates/credential/cargo-credential-wincred",
          -  "src/tools/rustdoc",
          -  "src/tools/rls",
          +  # "src/tools/cargo",
          +  # "src/tools/cargo/crates/credential/cargo-credential-1password",
          +  # "src/tools/cargo/crates/credential/cargo-credential-macos-keychain",
          +  # "src/tools/cargo/crates/credential/cargo-credential-wincred",
          +  # "src/tools/rustdoc",
          +  # "src/tools/rls",
          @@ -32 +32 @@ members = [
          -  "src/tools/rustdoc-themes",
          +  # "src/tools/rustdoc-themes",
          @@ -36 +36 @@ members = [
          -  "src/tools/html-checker",
          +  # "src/tools/html-checker",
          EOF
          )


      - name: cargo fetch
        continue-on-error: true
        run: |
          cd ${{matrix.target-path}}
          if [[ ${{matrix.target}} == webrender ]]; then
            # https://github.com/rust-lang/rust-analyzer/issues/9997
            cargo update -p url --precise 1.6.1
          fi
          cargo fetch --locked
          # This fails for webrender
          cargo check --all-targets

      - name: Warm up (build scripts, etc.)
        run: time ${{needs.build.outputs.ra-baseline}} -q analysis-stats --skip-inference ${{matrix.target-path}}

      # - name: analysis-stats baseline
      #   run: ${{needs.build.outputs.ra-baseline}} -q analysis-stats ${{matrix.target-path}}
      # - name: analysis-stats topic
      #   run: ${{needs.build.outputs.ra-topic}} -q analysis-stats ${{matrix.target-path}}

      - name: diagnostics baseline
        continue-on-error: true
        run: time ${{needs.build.outputs.ra-baseline}} -q diagnostics --disable-build-scripts ${{matrix.target-path}} > baseline.log
      - name: diagnostics topic
        continue-on-error: true
        run: time ${{needs.build.outputs.ra-topic}} -q diagnostics --disable-build-scripts ${{matrix.target-path}} > topic.log

      - name: Diff diagnostics
        continue-on-error: true
        run: git diff --no-index baseline.log topic.log | tee diag-${{matrix.target-repo}}.diff

      - uses: actions/upload-artifact@v2
        with:
          name: diag-${{matrix.target-repo}}.diff
          path: diag-${{matrix.target-repo}}.diff

  # diff:
  #   name: Diff stats
  #   needs: analysis-stats
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       # target: [self, ripgrep, webrender, diesel, creusot]
  #       target: [self, ripgrep, webrender, creusot]
  #     fail-fast: false
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: stat-${{matrix.target}}-baseline
  #         path: stats
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: stat-${{matrix.target}}-topic
  #         path: stats

  #     - name: Check type stats differ
  #       continue-on-error: true
  #       run: |
  #         ls -l stats/
  #         if ! diff <(grep '^  exprs:' stats/${{matrix.target}}-baseline) <(grep '^  exprs:' stats/${{matrix.target}}-topic); then
  #           git diff --no-index stats/* > type_stats-${{matrix.target}}.diff
  #         fi

  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: type_stats-${{matrix.target}}.diff
  #         path: type_stats-${{matrix.target}}.diff

  #     - name: fail if type stats differ
  #       run: diff <(grep '^  exprs:' stats/${{matrix.target}}-baseline) <(grep '^  exprs:' stats/${{matrix.target}}-topic)
